pensionCredits <- '{
	"database": "str:database:PC",
"measures": ["str:count:PC:V_F_PC_CASELOAD"],
"recodes": {
"str:field:PC:V_F_PC_CASELOAD:COA_CODE": {
"map": [
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000033"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000034"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000041"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000035"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000036"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000005"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000006"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000042"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000008"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000009"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000010"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000011"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000014"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000015"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000043"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000017"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000018"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000019"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000020"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000013"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000021"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000044"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000023"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000024"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000038"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000026"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000027"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000028"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000029"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000030"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000039"],
["str:value:PC:V_F_PC_CASELOAD:COA_CODE:V_C_GEOG05_LA_to_REGION:S12000040"]
],
"total": false
},
"str:field:PC:V_F_PC_CASELOAD:CNAGE": {
"map": [
["str:value:PC:V_F_PC_CASELOAD:CNAGE:C_PC_AGE_BAND:1"],
["str:value:PC:V_F_PC_CASELOAD:CNAGE:C_PC_AGE_BAND:2"],
["str:value:PC:V_F_PC_CASELOAD:CNAGE:C_PC_AGE_BAND:3"],
["str:value:PC:V_F_PC_CASELOAD:CNAGE:C_PC_AGE_BAND:4"],
["str:value:PC:V_F_PC_CASELOAD:CNAGE:C_PC_AGE_BAND:5"],
["str:value:PC:V_F_PC_CASELOAD:CNAGE:C_PC_AGE_BAND:6"],
["str:value:PC:V_F_PC_CASELOAD:CNAGE:C_PC_AGE_BAND:7"],
["str:value:PC:V_F_PC_CASELOAD:CNAGE:C_PC_AGE_BAND:999"]
],
"total": false
},
"str:field:PC:V_F_PC_CASELOAD:PCTYPE": {
"map": [
["str:value:PC:V_F_PC_CASELOAD:PCTYPE:C_PC_PCTYPE:1"],
["str:value:PC:V_F_PC_CASELOAD:PCTYPE:C_PC_PCTYPE:2"],
["str:value:PC:V_F_PC_CASELOAD:PCTYPE:C_PC_PCTYPE:3"],
["str:value:PC:V_F_PC_CASELOAD:PCTYPE:C_PC_PCTYPE:4"]
],
"total": false
},
"str:field:PC:F_PC_QTR:DATE_NAME": {
"map": [
["str:value:PC:F_PC_QTR:DATE_NAME:C_PC_QTR:201802"]
],
"total": false
},
"str:field:PC:V_F_PC_CASELOAD:CCSEX": {
"map": [
["str:value:PC:V_F_PC_CASELOAD:CCSEX:C_PC_CCSEX:1"],
["str:value:PC:V_F_PC_CASELOAD:CCSEX:C_PC_CCSEX:2"],
["str:value:PC:V_F_PC_CASELOAD:CCSEX:C_PC_CCSEX:99"]
],
"total": false
},
"str:field:PC:V_F_PC_CASELOAD:CTDURTN": {
"map": [
["str:value:PC:V_F_PC_CASELOAD:CTDURTN:C_PC_DURTN:1"],
["str:value:PC:V_F_PC_CASELOAD:CTDURTN:C_PC_DURTN:2"],
["str:value:PC:V_F_PC_CASELOAD:CTDURTN:C_PC_DURTN:3"],
["str:value:PC:V_F_PC_CASELOAD:CTDURTN:C_PC_DURTN:4"],
["str:value:PC:V_F_PC_CASELOAD:CTDURTN:C_PC_DURTN:5"],
["str:value:PC:V_F_PC_CASELOAD:CTDURTN:C_PC_DURTN:6"],
["str:value:PC:V_F_PC_CASELOAD:CTDURTN:C_PC_DURTN:999"]
],
"total": false
}
},
"dimensions": [
["str:field:PC:V_F_PC_CASELOAD:COA_CODE"],
["str:field:PC:F_PC_QTR:DATE_NAME"],
["str:field:PC:V_F_PC_CASELOAD:CNAGE"],
["str:field:PC:V_F_PC_CASELOAD:CTDURTN"],
["str:field:PC:V_F_PC_CASELOAD:CCSEX"],
["str:field:PC:V_F_PC_CASELOAD:AMTGP"],
["str:field:PC:V_F_PC_CASELOAD:PTNR"],
["str:field:PC:V_F_PC_CASELOAD:PCTYPE"]
]
}'
